import axiosInstance from "@/utils/axiosInstance";
import { House } from "@/types/models";

const homePath = "/house"; // Adjusted to the new API path

// Fetch homes with optional search and region parameters
export const fetchHouses = async (search: string = "", regionId?: number) => {
  try {
    const response = await axiosInstance.get(homePath, {
      params: { search, regionId },
    });
    return { success: true, data: response.data };
  } catch (error) {
    console.error("Error fetching homes:", error);
    return { success: false, error };
  }
};

export const filterHouses = async (
  search: string = "",
  spaceForPeople?: number,
  regionId?: number
) => {
  try {
    const response = await axiosInstance.get(homePath + "/filter", {
      params: {
        search,
        spaceForPeople,
        regionId, // Include regionId for filtering by region
      },
    });
    return { success: true, data: response.data };
  } catch (error) {
    console.error("Error fetching homes:", error);
    return { success: false, error };
  }
};

// Update home data
export const updateHouse = async (homeData: House) => {
  try {
    const response = await axiosInstance.put(
      `${homePath}/${homeData.id}`,
      homeData
    );
    return { success: true, data: response.data };
  } catch (error) {
    console.error("Error updating home:", error);
    return { success: false, error };
  }
};

// Add a new home (omit the ID as it will be generated by the database)
export const addHouse = async (homeData: Omit<House, "id">) => {
  try {
    const response = await axiosInstance.post(`${homePath}/create`, homeData);
    return { success: true, data: response.data };
  } catch (error) {
    console.error("Error adding home:", error);
    return { success: false, error };
  }
};

// Delete a home by ID
export const deleteHouse = async (id: number) => {
  try {
    const response = await axiosInstance.delete(`${homePath}/${id}`);
    return { success: true, data: response.data };
  } catch (error) {
    console.error("Error deleting home:", error);
    return { success: false, error };
  }
};

// services/house.ts

export const reportHouse = async (reportData: {
  houseId: number;
  message: string;
}) => {
  try {
    const response = await axiosInstance.post("/reports", reportData);
    return { success: true, data: response.data };
  } catch (error) {
    console.error("Error reporting house:", error);
    throw error;
  }
};
